
What is PyTorch?
================
https://pytorch.org/docs/stable/index.html

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


NumPy Bridge
------------
1. Tensors are similar to NumPy’s arrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.  

2. All the Tensors on the CPU except a CharTensor support converting to
NumPy and back. Converting a Torch Tensor to a NumPy array and vice versa is a breeze.  

3. The Torch Tensor and NumPy array will share their underlying memory
locations (if the Torch Tensor is on CPU), and changing one will change
the other.

In [15]:
import torch
import numpy as np 

#### GPU available

In [16]:
# Examine your GPUs are available for pytorch (False for CPU version of pytorch)
torch.cuda.is_available()

False

#### array <-> tensor

In [17]:
data = [[1, 2],[3, 4]]
# the difference between tensor & array is that:
# tensor is a data structure that is used in deep learning frameworks like PyTorch and TensorFlow
# while an array is a more general data structure that can be used in many programming languages.
# Tensors can have more than two dimensions, while arrays are typically limited to two dimensions.
# Tensors also have additional functionality for automatic differentiation and GPU acceleration,
# which makes them more suitable for deep learning tasks.

# tensor to array
x_tensor = torch.tensor(data); print(x_tensor)
x_tensor2array = x_tensor.numpy(); print(x_tensor2array); print()

# array to tensor
x_array = np.array(data); print(x_array)
x_array2tenor = torch.from_numpy(x_array); print(x_array2tenor)

tensor([[1, 2],
        [3, 4]])
[[1 2]
 [3 4]]

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])


## Define tensor

In [18]:
data = [[1, 2],[3, 4]]
x = torch.tensor(data); print(x)

tensor([[1, 2],
        [3, 4]])


In [19]:
# empty/rand/ones/zeros/eye(), xxx_like()
# the difference is you can fill dimensions without brackets at the beginning for these functions
x = torch.empty(2, 3); print(x)
x = torch.rand(2, 3); print(x) # initialization from the Gaussian distribution of N(0,1)
# cuda() means translating your tensors into GPUs
x = torch.zeros(2, 3, dtype=torch.float)#.cuda(); 
print(x) # if your device is CPU, please delete the cuda()
y = torch.rand_like(x) # _like means the same shape, data type and device(GPU or CPU)
print(y) 

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.0232, 0.9504, 0.8258],
        [0.2176, 0.1786, 0.0242]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.4640, 0.7372, 0.4333],
        [0.4729, 0.8401, 0.9576]])


In [20]:
# get shape
print(x.shape)
print(x.size())

torch.Size([2, 3])
torch.Size([2, 3])


If you have a one element tensor, use ``.item()`` to get the value as a Python number

In [21]:
x = torch.randn(1)
print(x)
print(x.item())
# .item() is used to get the value of a single-element tensor as a standard Python number.

tensor([1.0850])
1.0849664211273193


#### A bunch of operations in numpy have corresponding functions in torch

In [22]:
torch.arange(10)
# torch.stack()
# torch.concatenate()
# torch.squeeze()/unsqueeze()
# torch.flatten()

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# permute -> transpose in numpy, to switch the order of dimensions
x = torch.arange(24).reshape(2,3,4)
y = x.permute([2,0,1]); print(y.shape)
# original third dimension becomes the first dimension,
# original first dimension becomes the second dimension,
# original second dimension becomes the third dimension.

# original shape: (2, 3, 4) -> new shape: (4, 2, 3)

torch.Size([4, 2, 3])


## Computation of Tensors
Note: The default calculation is element-wise calculation (+ - * /)

In [24]:
x = torch.arange(6).reshape(2,3); print(x)
y = torch.rand(2, 3)
print(x + y)
print(x*y)
print(x/y)
# default calculation is element-wise!!!

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0.0282, 1.8262, 2.7902],
        [3.9808, 4.2898, 5.6702]])
tensor([[0.0000, 0.8262, 1.5804],
        [2.9425, 1.1590, 3.3511]])
tensor([[ 0.0000,  1.2104,  2.5310],
        [ 3.0586, 13.8048,  7.4603]])


### Matrix Multiplication

In [25]:
# torch.mul() equals "*": Element-wise multiplication
a = torch.rand(2, 3);print(a)
b = torch.rand(2, 3);print(b)
print(torch.mul(a, b))
print(torch.mul(a, b).size())
print((a*b))
print((a*b).shape)
# mul() is used for element-wise multiplication of two tensors.

tensor([[0.1493, 0.5253, 0.4579],
        [0.5961, 0.9828, 0.3302]])
tensor([[0.6057, 0.0083, 0.2681],
        [0.8310, 0.0790, 0.3494]])
tensor([[0.0904, 0.0044, 0.1227],
        [0.4954, 0.0777, 0.1154]])
torch.Size([2, 3])
tensor([[0.0904, 0.0044, 0.1227],
        [0.4954, 0.0777, 0.1154]])
torch.Size([2, 3])


In [26]:
# torch.mm(): the common mathematical matrix multiplication
mat1 = torch.randn(2, 3)
mat2 = torch.randn(3, 3)
print(torch.mm(mat1, mat2).size())
print((mat1 @ mat2).shape)

# mm() is used for matrix multiplication of two tensors (not element-wise multiplication).

torch.Size([2, 3])
torch.Size([2, 3])


In [27]:
# torch.matmul() equals "@": Matrix product of two tensors, it includes matrix multiplication methods of different dimensions
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(10, 4, 5)
torch.matmul(tensor1, tensor2).size()

torch.Size([10, 3, 5])

**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described [here](https://pytorch.org/docs/torch).

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [28]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
x = torch.arange(6).reshape(2,3) # x created in CPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    # y.cuda() is also an easy method to move onto the default GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

## Exercise1
Broadcasting is an underlying rules for dealing with unpaired tensors.  
[Broadcasting tutorial](https://deeplearninguniversity.com/pytorch/pytorch-broadcasting/)

## Exercise2
[Pytorch official website](https://pytorch.org/tutorials/) has provided sufficient tutorials for beginners.
Familiarize yourself with PyTorch concepts and modules. Learn how to load data, build deep neural networks, train and save your models in [quickstart guide](https://pytorch.org/tutorials/beginner/basics/intro.html).

We also provide old version of the pytorch tutorials in file folder "old_pytorch_tutorials". The tutorials in [Pytorch official website](https://pytorch.org/tutorials/) is more recommended.
